name: LaTeX compilation
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: aruneko/texlive
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        run: lualatex math.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: math
          path: math.pdf